---
title: "Youth, technology, and social media in East Africa, the Middle East, and Indigenous Canada"
date: "March 2016."
output:
  html_document:
    theme: cerulean
    toc: true
    toc_depth: 4
  pdf_document: default
---

<!-- For more info on RMarkdown see http://rmarkdown.rstudio.com/ -->

<!-- Enter the code required to load your data in the space below. The data will be loaded but the line of code won't show up in your write up (echo=FALSE) in order to save space-->


<!-- In the remainder of the document, add R code chunks as needed -->

### Introduction:

In September 2015, twenty youth from Kenya, Rwanda, Ethiopia, Uganda, Tanzania, Lebanon, and Indigenous Canada embarked on a project to survey their peers about how they are using technology and social media for work, income, learning, leadership, and employment. 580 youth from urban, peri-urban, and rural areas were surveyed through face-to-face qualitative and quantitative interviews.

The result of this exercise is a raw dataset of 580 responses and more than 1600 variables. 

Problem:

How are youth in Kenya, Rwanda, Ethiopia, Uganda, Tanzania, Lebanon, and Indigenous Canada  using technology and social media for work, income, learning, leadership, and employment?

Questions we are seeking to answer (students should choose three for analysis): 

* How does access to technology vary by gender?
* How does use of social media for work, income, learning, leadership, and employment vary by gender?
* In what ways are youth in these countries using technology and social media to support or engage in formal work? Informal work?
* In what ways are youth in these countries using technology and social media to supplement income, or to support primary incomes?
* In what ways are youth in these countries using technology and social media for learning?
* What barriers and incentives to online learning are there among the surveyed youth?
* How are young people positioning themselves as leaders in their communities or among peer groups using social media and technology?
* How are young people gaining and/or participating in formal or informal employment using technology and social media?

### Data:

Read raw excel table

```{r echo=FALSE}
#580 observatios 1024 variable
df=read.csv("survey.csv")
dim(df)
```

Insert data section here...

### Exploratory data analysis:

Insert exploratory data analysis here...

### Inference:

Insert inference section here...

### Conclusion:

Insert conclusion here...

### References:

Insert references here...

### Appendix:

Insert appendix here...